services:
  nginx:
    image: tugboatqa/nginx:latest
    default: true

    commands:
      init:
        # Install node 15
        - curl -sL https://deb.nodesource.com/setup_15.x | sudo -E bash -
        - apt-get install -y nodejs

        - npm install lerna --global
        - npm run install:dependencies

      build:
        - npm run -C "${TUGBOAT_ROOT}/packages/phoenix-ng" build -- --prod --output-path ${TUGBOAT_ROOT}/tugboat-build --base-href "./" && cp ${TUGBOAT_ROOT}/tugboat-build/index.html ${TUGBOAT_ROOT}/tugboat-build/404.html
        - ln -snf "${TUGBOAT_ROOT}/tugboat-build" "${DOCROOT}"
